# Generated by Django 4.2.1 on 2023-06-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='oai_metadata_format',
            field=models.CharField(choices=[('oai_dc', 'Dublin Core'), ('marc21', 'MARC XML')], default='oai_dc', max_length=32),
        ),
        migrations.AddField(
            model_name='site',
            name='oai_set',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
